# version: '3.8'
# services:
#   mysql:
#     image: mysql:8.0
#     container_name: pleague-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: 12345678
#       MYSQL_DATABASE: pleague
#     ports:
#       - "3306:3306"
#     networks:
#       - pleague-network

#   backend:
#     build:
#       context: ./BackendJava
#       dockerfile: Dockerfile
#     depends_on:
#       - mysql
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdatabase
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: 12345678
#     networks:
#       - pleague-network
  


# networks:
#   pleague-network:
#     driver: bridge

version: '3.8'

services:
  test-mysql:
    image: mysql:latest
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pleague
    ports:
      - "3307:3306"
    networks:
      - pleague-network

  frontend:
    build:
      context: ./Frontend/latest
      dockerfile: Dockerfile
    container_name: pleague-frontend
    ports:
      - "5173:5173"
    networks:
      - pleague-network

  pleague-backend:
    build:
      context: ./BackendJava
      dockerfile: Dockerfile
    container_name: pleague-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://test-mysql:3306/pleague
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - test-mysql
    ports:
      - "8080:8080"
    networks:
      - pleague-network

networks:
  pleague-network:
    driver: bridge
